/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SignalDirection = IDL.Variant({
  'put' : IDL.Null,
  'call' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Promotion = IDL.Record({
  'id' : IDL.Text,
  'bonusAmount' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'validUntil' : IDL.Int,
});
export const Signal = IDL.Record({
  'id' : IDL.Text,
  'direction' : SignalDirection,
  'asset' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'expiryMinutes' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'status' : UserStatus,
  'paymentMethod' : IDL.Text,
  'balance' : IDL.Int,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
  'transactionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'balance' : IDL.Int,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DepositRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : DepositStatus,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const PaymentInfo = IDL.Record({
  'bkashNumber' : IDL.Text,
  'binanceId' : IDL.Text,
  'nagadNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateUser' : IDL.Func([IDL.Text], [], []),
  'addPromotion' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int], [], []),
  'addSignal' : IDL.Func([IDL.Text, SignalDirection, IDL.Nat, IDL.Nat], [], []),
  'approveDepositRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDepositRequest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'deactivateUser' : IDL.Func([IDL.Text], [], []),
  'deletePromotion' : IDL.Func([IDL.Text], [], []),
  'deleteSignal' : IDL.Func([IDL.Text], [], []),
  'getActivePromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getActiveSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getPaymentInfo' : IDL.Func([], [PaymentInfo], ['query']),
  'getPendingUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getUserBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatus' : IDL.Func([], [UserStatus], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'processWithdrawalRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePaymentInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SignalDirection = IDL.Variant({ 'put' : IDL.Null, 'call' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Promotion = IDL.Record({
    'id' : IDL.Text,
    'bonusAmount' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'validUntil' : IDL.Int,
  });
  const Signal = IDL.Record({
    'id' : IDL.Text,
    'direction' : SignalDirection,
    'asset' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'expiryMinutes' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'status' : UserStatus,
    'paymentMethod' : IDL.Text,
    'balance' : IDL.Int,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
    'transactionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'balance' : IDL.Int,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DepositRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : DepositStatus,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const PaymentInfo = IDL.Record({
    'bkashNumber' : IDL.Text,
    'binanceId' : IDL.Text,
    'nagadNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateUser' : IDL.Func([IDL.Text], [], []),
    'addPromotion' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int], [], []),
    'addSignal' : IDL.Func(
        [IDL.Text, SignalDirection, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'approveDepositRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDepositRequest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'deactivateUser' : IDL.Func([IDL.Text], [], []),
    'deletePromotion' : IDL.Func([IDL.Text], [], []),
    'deleteSignal' : IDL.Func([IDL.Text], [], []),
    'getActivePromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getActiveSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getPaymentInfo' : IDL.Func([], [PaymentInfo], ['query']),
    'getPendingUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getUserBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatus' : IDL.Func([], [UserStatus], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'processWithdrawalRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePaymentInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };