/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SignalDirection = IDL.Variant({
  'put' : IDL.Null,
  'call' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Signal = IDL.Record({
  'id' : IDL.Text,
  'direction' : SignalDirection,
  'asset' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'expiryMinutes' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'status' : UserStatus,
  'paymentMethod' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
  'transactionId' : IDL.Text,
});
export const PaymentInfo = IDL.Record({
  'bkashNumber' : IDL.Text,
  'binanceId' : IDL.Text,
  'nagadNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateUser' : IDL.Func([IDL.Text], [], []),
  'addSignal' : IDL.Func([IDL.Text, SignalDirection, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateUser' : IDL.Func([IDL.Text], [], []),
  'deleteSignal' : IDL.Func([IDL.Text], [], []),
  'getActiveSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentInfo' : IDL.Func([], [PaymentInfo], ['query']),
  'getPendingUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getSignals' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], ['query']),
  'getUserStatus' : IDL.Func([IDL.Text], [UserStatus], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updatePaymentInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SignalDirection = IDL.Variant({ 'put' : IDL.Null, 'call' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Signal = IDL.Record({
    'id' : IDL.Text,
    'direction' : SignalDirection,
    'asset' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'expiryMinutes' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'status' : UserStatus,
    'paymentMethod' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
    'transactionId' : IDL.Text,
  });
  const PaymentInfo = IDL.Record({
    'bkashNumber' : IDL.Text,
    'binanceId' : IDL.Text,
    'nagadNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateUser' : IDL.Func([IDL.Text], [], []),
    'addSignal' : IDL.Func(
        [IDL.Text, SignalDirection, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateUser' : IDL.Func([IDL.Text], [], []),
    'deleteSignal' : IDL.Func([IDL.Text], [], []),
    'getActiveSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentInfo' : IDL.Func([], [PaymentInfo], ['query']),
    'getPendingUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getSignals' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], ['query']),
    'getUserStatus' : IDL.Func([IDL.Text], [UserStatus], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updatePaymentInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };