/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PaymentInfo {
  'bkashNumber' : string,
  'binanceId' : string,
  'nagadNumber' : string,
}
export interface Signal {
  'id' : string,
  'direction' : SignalDirection,
  'asset' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'expiryMinutes' : bigint,
  'accuracy' : bigint,
}
export type SignalDirection = { 'put' : null } |
  { 'call' : null };
export interface User {
  'id' : string,
  'status' : UserStatus,
  'paymentMethod' : string,
  'name' : string,
  'phone' : string,
  'registeredAt' : bigint,
  'transactionId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateUser' : ActorMethod<[string], undefined>,
  'addSignal' : ActorMethod<
    [string, SignalDirection, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateUser' : ActorMethod<[string], undefined>,
  'deleteSignal' : ActorMethod<[string], undefined>,
  'getActiveSignals' : ActorMethod<[], Array<Signal>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaymentInfo' : ActorMethod<[], PaymentInfo>,
  'getPendingUsers' : ActorMethod<[], Array<User>>,
  'getSignals' : ActorMethod<[string], Array<Signal>>,
  'getUserStatus' : ActorMethod<[string], UserStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, string, string], boolean>,
  'updatePaymentInfo' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];